// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20220203121342_AddColorProperty")]
    partial class AddColorProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ParkingCost")
                        .HasColumnType("float");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volvo",
                            CheckIn = new DateTime(2022, 2, 3, 12, 13, 42, 73, DateTimeKind.Local).AddTicks(1484),
                            Color = "Röd",
                            Model = "V70",
                            RegNo = "ABC123",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Messerschitt",
                            CheckIn = new DateTime(2022, 2, 3, 12, 58, 42, 73, DateTimeKind.Local).AddTicks(1545),
                            Color = "Silver",
                            Model = "KR 200",
                            RegNo = "ABC456",
                            VehicleType = 0,
                            Wheels = 3
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Honda",
                            CheckIn = new DateTime(2022, 2, 3, 12, 43, 42, 73, DateTimeKind.Local).AddTicks(1549),
                            Color = "Svart",
                            Model = "CB 125T",
                            RegNo = "ABC789",
                            VehicleType = 4,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 4,
                            Brand = "MAN",
                            CheckIn = new DateTime(2022, 2, 3, 13, 8, 42, 73, DateTimeKind.Local).AddTicks(1552),
                            Color = "Blå",
                            Model = "X-2000",
                            RegNo = "DEF123",
                            VehicleType = 2,
                            Wheels = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nautor Swan",
                            CheckIn = new DateTime(2022, 1, 4, 13, 13, 42, 73, DateTimeKind.Local).AddTicks(1555),
                            Color = "Vit",
                            Model = "Swan 66",
                            RegNo = "DEF456",
                            VehicleType = 1,
                            Wheels = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
